version: 2
jobs:
  build:
    working_directory: ~/slang-studio
    docker:
    - image: bitspark/slang-ci:latest
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: Test
        command: npm test