version: 2
jobs:
  build:
    working_directory: ~/slang-studio
    docker:
      - image: bitspark/slang-ci:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run-script build

  test:
    working_directory: ~/slang-studio
    docker:
    - image: bitspark/slang-ci:latest
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Test
        command: npm test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
