version: 2
jobs:
  build:
    working_directory: ~/slang-editor
    docker:
      - image: bitspark/slang-ci:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          environment:
            apiUrl: /
            baseHref: /app/
          command: npm run-script package

  lint:
    working_directory: ~/slang-editor
    docker:
      - image: bitspark/slang-ci:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint

  deps:
    working_directory: ~/slang-editor
    docker:
      - image: bitspark/slang-ci:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Check dependencies
          command: npm run validate:deps

  test:
    working_directory: ~/slang-editor
    docker:
    - image: bitspark/slang-ci:latest
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Test
        command: npm test

  publish:
    working_directory: ~/slang-editor
    docker:
    - image: bitspark/slang-ci:latest
    steps:
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/slang-editor/.npmrc
    - run:
        name: Build package
        command: npm run package
    - run:
        name: Publish package
        command: cd dist && npm publish


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - lint:
          requires:
            - build
      - deps:
          requires:
            - build
      - test:
          requires:
            - build
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build